### PR TITLE
Use ToastifyJs to replace alerts

### PR DESCRIPTION
**Pull request by timobraz**
## Description
All alerts are replaced with a toast popup in bottom left with the signature peterportal color.

## Screenshots
image

## Steps to verify/test this change:

- [ ] Verify changes work as expected on staging instance

## Final Checks:

- [ ] Verify successful deployment

(optional)

- [ ] Write tests
- [ ] Write documentation

## Issues

Closes #

### CODE REVIEW

**Review by js0mmer — COMMENTED** [review]
Could you update the of the hook function/calls to be consistent? For a hook, `useToastify` would be a preferred name over `toaster`.

Also, I think having the error toasts in red would be better, blue for only the info toasts. The hook could take an argument where we specify the type of toast as 'info' or 'error' and the color is adjusted accordingly. Thoughts @Awesome-E?

**Comment by timobraz** [comment]
I did that originally and the linter complains because it's used in cotext files.

**Comment by timobraz** [comment]
I think I'll instead just move it out of the hooks folder and into lib.

**Comment by js0mmer** [comment]
> I think I'll instead just move it out of the hooks folder and into lib.

Ok, that sounds fine. I guess it's not really a hook? You can move it out and just call it toaster.

**Comment by Awesome-E** [comment]
> Also, I think having the error toasts in red would be better, blue for only the info toasts. The hook could take an argument where we specify the type of toast as 'info' or 'error' and the color is adjusted accordingly. Thoughts @Awesome-E?

I think that makes sense yeah.


> I guess it's not really a hook?

Yeah it should be treated more like a helper function, not really a hook

**Review by js0mmer — APPROVED** [review]

**Pull request merged**
