### PR TITLE
Clean up Roadmap Year/Quarter Styles

### PR DESCRIPTION
**Pull request by Awesome-E**
## Screenshots

Before:
image
After:
image

## Steps to verify/test this change:

- [ ] Verify changes work as expected on staging instance

## Final Checks:

- [ ] Verify successful deployment

### CODE REVIEW

**Review by js0mmer — COMMENTED** [review]
Haven't looked at any code yet but visually it looks pretty good!

A couple things that stood out to me were:
1. The context menu for quarters gets chopped off when all the quarters in that row are empty
image
3. When a user first opens the roadmap, I don't think they'll know how to interact with the roadmap when they just see 3 rectangles with quarter names. This ties back to your point about the necessity of an onboarding tutorial but I also think that something as small as adding a message into the empty quarter saying "No courses added yet! Drag a course from the search sidebar on the right to start building your planner." could make it much easier for new users to understand what they're looking at and how to interact with it. Thoughts?
image

**Comment by Awesome-E** [comment]
image
This commit should address both issues

**Review by js0mmer — CHANGES_REQUESTED** [review]
One last thing I just noticed. The add course buttons are missing on mobile

image

**Comment by Awesome-E** [comment]
This should be fixed now

**Review by js0mmer — APPROVED** [review]
LGTM

**Pull request merged**
